### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required 'apps/user_pwauth/user_pwauth.php' 

### ISSUE THREAD

**Issue by pmetras** [veretcle/nextcloud-user_pwauth#2]
It seems that the inclusion path for apps is different from ownCloud. There's a fatal error from nextCloud cron job when trying to include user_pwauth.php.

`PHP Fatal error:  require_once(): Failed opening required 'apps/user_pwauth/user_pwauth.php' (include_path='/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/apps') in /var/www/nextcloud/apps/user_pwauth/appinfo/app.php on line 28`

Line 28 of file 'apps/user_pwauth/appinfo/app.php' must be changed to `require_once('user_pwauth/user_pwauth.php');`

**Comment by veretcle** [comment]
Got the same issue #1 with a different path.

I'll try to find something that works for all version of ownCloud/NextCloud.

**Comment by veretcle** [comment]
I think I got the solution for it to be compatible with almost every version of nextcloud/owncloud. Will apply this as soon as I can.

**Comment by veretcle** [comment]
Finally fixed it. Sorry for the very long time. It is actually not useful at all to add this line.

I'll test it a few days just to be sure before re-pushing it to nextcloud apps.
