### ISSUE TITLE
is it possiable to suppor change password?

### ISSUE THREAD

**Issue by starmoonxp** [veretcle/nextcloud-user_pwauth#3]
as title.

**Comment by veretcle** [comment]
Unfortunately no: most users would run ownCloud/NextCloud under the http user (user responsible for running their HTTP server/PHP renderer), so it would not have sufficient rights to change password.

Besides, password changing ability has only been added to the plugin (as an empty function) to allow for email change (those two different functions were linked in an early version of ownCloud).

So I'm sorry, won't happen.
