### ISSUE TITLE
Setting is broken

### ISSUE THREAD

**Issue by lxzheng** [veretcle/nextcloud-user_pwauth#7]
I got the "HTTP ERROR 405" when I modify the setting and press the save button.

This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 405

**Comment by moonwolf-github** [comment]
I can't confirm it now, but i had something similar when trying to change `pwauth` path (white screen IIRC).

**Comment by veretcle** [comment]
There are some glitches due to the integration of a certain PHP File at the wrong place. Can you please check with the latest version on the github repo?

**Comment by veretcle** [comment]
OK, I've tested so far I can confirm that there is an issue, but I cannot find where. I'm continuing the investigation…

**Comment by veretcle** [comment]
I have to rework everything to get it done properly. My app is using the VERY old API to register settings and it is in fact completely broken.

**Comment by veretcle** [comment]
It would take much more work than I expected to make the application compatible with NextCloud 12/13 again: the interface and integration has to be completely redone.

I'll try to fix as much as I can as soon as I can.

**Comment by veretcle** [comment]
Please try the release 2.5.0 : it fixes all the issues with the admin interface.
